#
# This is the rule used to build the Yoix script that stream edits some of
# the source files generated by YWAIT. It obviously assumes the definitions
# in variables.mk, which include $(GSUBSCRIPT), are all available, so only
# include this file after including variables.mk.
#

$(GSUBSCRIPT) : $(GSUBSCRIPT:.yx=._YX) $(ROOT)/make/variables.mk
	@echo "        sed -e ... $(GSUBSCRIPT:.yx=._YX) > $@"; \
	sed \
	    -e 's!<_ACRONYM_>!$(ACRONYM)!g' \
	    -e 's!<_ACRONYM_LOWER_>!$(ACRONYM_LOWER)!g' \
	    -e 's!<_ACRONYM_UPLOW_>!$(ACRONYM_UPLOW)!g' \
	    -e 's!<_BETA_PREFIX_>!$(BETA_PREFIX)!g' \
	    -e 's!<_COMMAND_PATHS_>!$(COMMAND_PATHS)!g' \
	    -e 's!<_FULLNAME_>!$(FULLNAME)!g' \
	    -e 's!<_GSUBSCRIPT_BASENAME_>!$(GSUBSCRIPT_BASENAME)!g' \
	    -e 's!<_JARFILE_BASENAME_>!$(JARFILE_BASENAME)!g' \
	    -e 's!<_JARFILE_RELEASE_>!$(JARFILE_RELEASE)!g' \
	    -e 's!<_JARFILE_RELEASE_DATE_>!$(JARFILE_RELEASE_DATE)!g' \
	    -e 's!<_JAVA_BIN_>!$(JAVA_BIN)!g' \
	    -e 's!<_PERL_PATH_>!$(PERL_PATH)!g' \
	    -e 's!<_PROPRIETARY_LABEL_>!$(PROPRIETARY_LABEL)!g' \
	    -e 's!<_SERVER_ALIAS_>!$(SERVER_ALIAS)!g' \
	    -e 's!<_SERVER_ALIAS_PREFIX_>!$(SERVER_ALIAS_PREFIX)!g' \
	    -e 's!<_SERVER_BASEURL_>!$(SERVER_BASEURL)!g' \
	    -e 's!<_SERVER_CGIBIN_>!$(SERVER_CGIBIN)!g' \
	    -e 's!<_SERVER_DOCDIR_>!$(SERVER_DOCDIR)!g' \
	    -e 's!<_SERVER_HOMEDIR_>!$(SERVER_HOMEDIR)!g' \
	    -e 's!<_SERVER_SCRIPTALIAS_>!$(SERVER_SCRIPTALIAS)!g' \
	    -e 's!<_SERVER_TYPE_>!$(SERVER_TYPE)!g' \
	    -e 's!<_USER_NAME_>!$(USER_NAME)!g' \
	    -e 's!<_OWNER_>!$(OWNER)!g' \
	    -e 's!<_SUBOWNER_>!$(SUBOWNER)!g' \
	    -e 's!<_YOIX_FONTOPTION_>!$(YOIX_FONTOPTION)!g' \
	< $(GSUBSCRIPT:.yx=._YX) > $@

