/*
 *  This software may only be used by you under license from AT&T Corp.
 *  ("AT&T").  A copy of AT&T's Source Code Agreement is available at
 *  AT&T's Internet website having the URL:
 *
 *    <http://www.research.att.com/sw/tools/yoix/license/source.html>
 *
 *  If you received this software without first entering into a license
 *  with AT&T, you have an infringing copy of this software and cannot
 *  use it without violating AT&T's intellectual property rights.
 */

package att.research.yoix;
import java.awt.*;

abstract
class YoixModuleAWT extends YoixModule

    implements YoixConstantsAWT,
	       YoixConstantsImage

{

    static String  $MODULENAME = M_AWT;

    static String  $YOIXCONSTANTSAWT = YOIXPACKAGE + ".YoixConstantsAWT";
    static String  $YOIXCONSTANTSJFC = YOIXPACKAGE + ".YoixConstantsJFC";

    //
    // Default constants
    //

    static Dimension  $DEFAULTSIZE = new Dimension(576, 432);
    static Integer    $BUTTON1MASK = new Integer(YOIX_BUTTON1_MASK);
    static Integer    $STANDARDCURSOR = new Integer(V_STANDARD_CURSOR);
    static Integer    $TILEHINT = new Integer(YOIX_SCALE_TILE);
    static Double     $MEDIUMINSETS = new Double(2.0);
    static Point      $DEFAULTLOCATION = new Point(0, 0);

    static Object  $module[] = {
    //
    // NAME                          ARG                  COMMAND     MODE   REFERENCE
    // ----                          ---                  -------     ----   ---------
       null,                         "160",               $LIST,      $RORO, $MODULENAME,
       $YOIXCONSTANTSJFC,            "YOIX_\tYOIX_",      $READCLASS, $LR__, null,

       "addColor",                   "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "addCursor",                  "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "addEventHandler",            "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "addListener",                "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "appendText",                 "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "beep",                       "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "deleteText",                 "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "distance",                   "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "getBestCursorSize",          "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "getBrighterColor",           "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "getCMYKColor",               "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "getColorName",               "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "getDarkerColor",             "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "getFirstFocusComponent",     "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "getFocusComponentAfter",     "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "getFocusComponentBefore",    "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "getFocusComponents",         "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "getFocusOwner",              "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "getFontList",                "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "getHSBColor",                "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "getHSBComponents",           "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "getLastFocusComponent",      "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "getLocationInRoot",          "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "getLocationOnScreen",        "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "getMaximumCursorColors",     "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "getRGBColor",                "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "getSaturationAdjustedColor", "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "getScreenInsets",            "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "getScreenResolution",        "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "getScreenSize",              "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "insertText",                 "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "invokeLater",                "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "isDispatchThread",           "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "isFullScreenSupported",      "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "postEvent",                  "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "printAll",                   "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "removeEventHandler",         "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "removeListener",             "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "replaceText",                "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "toBack",                     "YoixModuleJFC",     $MODULE,    $LR_X, null,
       "toFront",                    "YoixModuleJFC",     $MODULE,    $LR_X, null,

       "Color",                      "YoixModuleJFC",     $MODULE,    $RORO, null,
       "Cursor",                     "YoixModuleJFC",     $MODULE,    $RORO, null,
       "KeyCode",                    "YoixModuleJFC",     $MODULE,    $RORO, null,
       "SystemColor",                "YoixModuleJFC",     $MODULE,    $RORO, null,

    //
    // AWT types
    //

       T_MENUBAR,                    "9",                 $DICT,      $L___, T_MENUBAR,
       null,                         "-1",                $GROWTO,    null,  null,
       N_MAJOR,                      $COMPONENT,          $INTEGER,   $LR__, null,
       N_MINOR,                      $MENUBAR,            $INTEGER,   $LR__, null,
       N_FONT,                       T_OBJECT,            $NULL,      $RW_,  null,
       N_GETENABLED,                 T_CALLABLE,          $NULL,      $L__X, null,
       N_GETSTATE,                   T_CALLABLE,          $NULL,      $L__X, null,
       N_ITEMS,                      T_MENU,              $NULL,      $RW_,  null,
       N_SETENABLED,                 T_CALLABLE,          $NULL,      $L__X, null,
       N_SETSTATE,                   T_CALLABLE,          $NULL,      $L__X, null,
       N_VISIBLE,                    $TRUE,               $INTEGER,   $RW_,  null,

       T_POPUPMENU,                  "11",                $DICT,      $L___, T_POPUPMENU,
       null,                         "-1",                $GROWTO,    null,  null,
       N_MAJOR,                      $COMPONENT,          $INTEGER,   $LR__, null,
       N_MINOR,                      $POPUPMENU,          $INTEGER,   $LR__, null,
       N_FONT,                       T_OBJECT,            $NULL,      $RW_,  null,
       N_GETENABLED,                 T_CALLABLE,          $NULL,      $L__X, null,
       N_GETSTATE,                   T_CALLABLE,          $NULL,      $L__X, null,
       N_ITEMS,                      T_MENU,              $NULL,      $RW_,  null,
       N_LOCATION,                   T_POINT,             $DECLARE,   $RW_,  null,
       N_SETENABLED,                 T_CALLABLE,          $NULL,      $L__X, null,
       N_SETSTATE,                   T_CALLABLE,          $NULL,      $L__X, null,
       N_TEXT,                       T_STRING,            $NULL,      $RW_,  null,
       N_VISIBLE,                    $FALSE,              $INTEGER,   $RW_,  null,

       T_ROWPROPERTIES,              "2",                 $DICT,      $L___, T_ROWPROPERTIES,
       N_BACKGROUND,                 T_ARRAY,             $NULL,      $RW_,  null,
       N_FOREGROUND,                 T_ARRAY,             $NULL,      $RW_,  null,

       T_CHECKBOXGROUP,              "5",                 $DICT,      $L___, T_CHECKBOXGROUP,
       null,                         "-1",                $GROWTO,    null,  null,
       N_MAJOR,                      $COMPONENT,          $INTEGER,   $LR__, null,
       N_MINOR,                      $CHECKBOXGROUP,      $INTEGER,   $LR__, null,
       N_ETC,                        T_OBJECT,            $NULL,      $LR__, null,
       N_MODEL,                      "0",                 $INTEGER,   $RW_,  null,
       N_SELECTED,                   $FALSE,              $OBJECT,    $RW_,  null,

       T_BUTTON,                     "22",                $DICT,      $L___, T_BUTTON,
       null,                         "-1",                $GROWTO,    null,  null,
       N_MAJOR,                      $COMPONENT,          $INTEGER,   $LR__, null,
       N_MINOR,                      $BUTTON,             $INTEGER,   $LR__, null,
       N_AUTOTRIM,                   $FALSE,              $INTEGER,   $RW_,  null,
       N_BACKGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_COMMAND,                    T_STRING,            $NULL,      $RW_,  null,
       N_CURSOR,                     $STANDARDCURSOR,     $OBJECT,    $RW_,  null,
       N_ENABLED,                    $TRUE,               $INTEGER,   $RW_,  null,
       N_ETC,                        T_OBJECT,            $NULL,      $LR__, null,
       N_FOCUSABLE,                  T_OBJECT,            $NULL,      $RW_,  null,
       N_FOCUSOWNER,                 $FALSE,              $INTEGER,   $LR__, null,
       N_FONT,                       T_OBJECT,            $NULL,      $RW_,  null,
       N_FOREGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_LOCATION,                   T_POINT,             $NULL,      $RW_,  null,
       N_POPUP,                      T_POPUPMENU,         $NULL,      $RW_,  null,
       N_REQUESTFOCUS,               $FALSE,              $INTEGER,   $RW_,  null,
       N_ROOT,                       T_OBJECT,            $NULL,      $LR__, null,
       N_SHOWING,                    $FALSE,              $INTEGER,   $LR__, null,
       N_SIZE,                       T_DIMENSION,         $NULL,      $RW_,  null,
       N_TAG,                        T_STRING,            $NULL,      $RW_,  null,
       N_TEXT,                       T_STRING,            $NULL,      $RW_,  null,
       N_UIMKEY,                     T_STRING,            $NULL,      $RW_,  null,
       N_VISIBLE,                    $TRUE,               $INTEGER,   $RW_,  null,

       T_CANVAS,                     "32",                $DICT,      $L___, T_CANVAS,
       null,                         "-1",                $GROWTO,    null,  null,
       N_MAJOR,                      $COMPONENT,          $INTEGER,   $LR__, null,
       N_MINOR,                      $CANVAS,             $INTEGER,   $LR__, null,
       N_BACKGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_BACKGROUNDHINTS,            $TILEHINT,           $INTEGER,   $RW_,  null,
       N_BACKGROUNDIMAGE,            T_OBJECT,            $NULL,      $RW_,  null,
       N_BORDER,                     T_OBJECT,            $NULL,      $RW_,  null,
       N_BORDERCOLOR,                T_COLOR,             $NULL,      $RW_,  null,
       N_BUTTONMASK,                 $BUTTON1MASK,        $INTEGER,   $RW_,  null,
       N_CURSOR,                     $STANDARDCURSOR,     $OBJECT,    $RW_,  null,
       N_ENABLED,                    $TRUE,               $INTEGER,   $RW_,  null,
       N_ETC,                        T_OBJECT,            $NULL,      $LR__, null,
       N_FOCUSABLE,                  T_OBJECT,            $NULL,      $RW_,  null,
       N_FOCUSOWNER,                 $FALSE,              $INTEGER,   $LR__, null,
       N_FONT,                       T_OBJECT,            $NULL,      $RW_,  null,
       N_FOREGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_GRAPHICS,                   T_GRAPHICS,          $NULL,      $RW_,  null,
       N_LOCATION,                   T_POINT,             $NULL,      $RW_,  null,
       N_MAXIMUMSIZE,                T_DIMENSION,         $NULL,      $RW_,  null,
       N_MINIMUMSIZE,                T_DIMENSION,         $NULL,      $RW_,  null,
       N_PAINT,                      T_CALLABLE,          $NULL,      $RWX,  null,
       N_POPUP,                      T_POPUPMENU,         $NULL,      $RW_,  null,
       N_PREFERREDSIZE,              T_DIMENSION,         $NULL,      $RW_,  null,
       N_REPAINT,                    T_CALLABLE,          $NULL,      $L__X, null,
       N_REQUESTFOCUS,               $FALSE,              $INTEGER,   $RW_,  null,
       N_ROOT,                       T_OBJECT,            $NULL,      $LR__, null,
       N_SHOWING,                    $FALSE,              $INTEGER,   $LR__, null,
       N_SIZE,                       T_DIMENSION,         $NULL,      $RW_,  null,
       N_STATE,                      $FALSE,              $INTEGER,   $RW_,  null,
       N_STICKY,                     $FALSE,              $INTEGER,   $RW_,  null,
       N_TAG,                        T_STRING,            $NULL,      $RW_,  null,
       N_UIMKEY,                     T_STRING,            $NULL,      $RW_,  null,
       N_VISIBLE,                    $TRUE,               $INTEGER,   $RW_,  null,

       T_CHECKBOX,                   "24",                $DICT,      $L___, T_CHECKBOX,
       null,                         "-1",                $GROWTO,    null,  null,
       N_MAJOR,                      $COMPONENT,          $INTEGER,   $LR__, null,
       N_MINOR,                      $CHECKBOX,           $INTEGER,   $LR__, null,
       N_AUTOTRIM,                   $FALSE,              $INTEGER,   $RW_,  null,
       N_BACKGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_COMMAND,                    T_STRING,            $NULL,      $RW_,  null,
       N_CURSOR,                     $STANDARDCURSOR,     $OBJECT,    $RW_,  null,
       N_ENABLED,                    $TRUE,               $INTEGER,   $RW_,  null,
       N_ETC,                        T_OBJECT,            $NULL,      $LR__, null,
       N_FOCUSABLE,                  T_OBJECT,            $NULL,      $RW_,  null,
       N_FOCUSOWNER,                 $FALSE,              $INTEGER,   $LR__, null,
       N_FONT,                       T_OBJECT,            $NULL,      $RW_,  null,
       N_FOREGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_GROUP,                      T_CHECKBOXGROUP,     $NULL,      $RW_,  null,
       N_LOCATION,                   T_POINT,             $NULL,      $RW_,  null,
       N_POPUP,                      T_POPUPMENU,         $NULL,      $RW_,  null,
       N_REQUESTFOCUS,               $FALSE,              $INTEGER,   $RW_,  null,
       N_ROOT,                       T_OBJECT,            $NULL,      $LR__, null,
       N_SHOWING,                    $FALSE,              $INTEGER,   $LR__, null,
       N_SIZE,                       T_DIMENSION,         $NULL,      $RW_,  null,
       N_STATE,                      $FALSE,              $INTEGER,   $RW_,  null,
       N_TAG,                        T_STRING,            $NULL,      $RW_,  null,
       N_TEXT,                       T_STRING,            $NULL,      $RW_,  null,
       N_UIMKEY,                     T_STRING,            $NULL,      $RW_,  null,
       N_VISIBLE,                    $TRUE,               $INTEGER,   $RW_,  null,

       T_CHOICE,                     "23",                $DICT,      $L___, T_CHOICE,
       null,                         "-1",                $GROWTO,    null,  null,
       N_MAJOR,                      $COMPONENT,          $INTEGER,   $LR__, null,
       N_MINOR,                      $CHOICE,             $INTEGER,   $LR__, null,
       N_BACKGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_CURSOR,                     $STANDARDCURSOR,     $OBJECT,    $RW_,  null,
       N_ENABLED,                    $TRUE,               $INTEGER,   $RW_,  null,
       N_ETC,                        T_OBJECT,            $NULL,      $LR__, null,
       N_FOCUSABLE,                  T_OBJECT,            $NULL,      $RW_,  null,
       N_FOCUSOWNER,                 $FALSE,              $INTEGER,   $LR__, null,
       N_FONT,                       T_OBJECT,            $NULL,      $RW_,  null,
       N_FOREGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_ITEMS,                      T_ARRAY,             $NULL,      $RW_,  null,
       N_LABELS,                     T_ARRAY,             $NULL,      $RW_,  null,
       N_LOCATION,                   T_POINT,             $NULL,      $RW_,  null,
       N_MAPPINGS,                   T_ARRAY,             $NULL,      $RW_,  null,
       N_POPUP,                      T_POPUPMENU,         $NULL,      $RW_,  null,
       N_REQUESTFOCUS,               $FALSE,              $INTEGER,   $RW_,  null,
       N_ROOT,                       T_OBJECT,            $NULL,      $LR__, null,
       N_SELECTED,                   T_OBJECT,            $NULL,      $RW_,  null,
       N_SHOWING,                    $FALSE,              $INTEGER,   $LR__, null,
       N_SIZE,                       T_DIMENSION,         $NULL,      $RW_,  null,
       N_TAG,                        T_STRING,            $NULL,      $RW_,  null,
       N_UIMKEY,                     T_STRING,            $NULL,      $RW_,  null,
       N_VISIBLE,                    $TRUE,               $INTEGER,   $RW_,  null,

       T_DIALOG,                     "42",                $DICT,      $L___, T_DIALOG,
       null,                         "-1",                $GROWTO,    null,  null,
       N_MAJOR,                      $COMPONENT,          $INTEGER,   $LR__, null,
       N_MINOR,                      $DIALOG,             $INTEGER,   $LR__, null,
       N_AUTODISPOSE,                $FALSE,              $INTEGER,   $RW_,  null,
       N_AUTORAISE,                  $TRUE,               $INTEGER,   $RW_,  null,
       N_BACKGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_BACKGROUNDHINTS,            $TILEHINT,           $INTEGER,   $RW_,  null,
       N_BACKGROUNDIMAGE,            T_OBJECT,            $NULL,      $RW_,  null,
       N_COMPONENTS,                 T_DICT,              $NULL,      $LR__, null,
       N_CURSOR,                     $STANDARDCURSOR,     $OBJECT,    $RW_,  null,
       N_DECORATIONSTYLE,            "1",                 $INTEGER,   $RW_,  null,
       N_DISPOSE,                    $FALSE,              $INTEGER,   $RW_,  null,
       N_ENABLED,                    $TRUE,               $INTEGER,   $RW_,  null,
       N_ETC,                        T_OBJECT,            $NULL,      $LR__, null,
       N_FIRSTFOCUS,                 $TRUE,               $INTEGER,   $RW_,  null,
       N_FOCUSABLE,                  T_OBJECT,            $NULL,      $RW_,  null,
       N_FOCUSOWNER,                 $FALSE,              $INTEGER,   $LR__, null,
       N_FONT,                       T_OBJECT,            $NULL,      $RW_,  null,
       N_FOREGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_FRONTTOBACK,                $TRUE,               $INTEGER,   $RW_,  null,
       N_FULLSCREEN,                 $FALSE,              $INTEGER,   $RW_,  null,
       N_GRAPHICS,                   T_GRAPHICS,          $NULL,      $RW_,  null,
       N_LAYOUT,                     T_ARRAY,             $NULL,      $RW_,  null,
       N_LAYOUTMANAGER,              T_BORDERLAYOUT,      $DECLARE,   $RW_,  null,
       N_LOCATION,                   $DEFAULTLOCATION,    $POINT,     $RW_,  null,
       N_MODAL,                      $FALSE,              $INTEGER,   $RW_,  null,
       N_NEXTCARD,                   T_OBJECT,            $NULL,      $RW_,  null,
       N_PAINT,                      T_CALLABLE,          $NULL,      $RWX,  null,
       N_PARENT,                     T_OBJECT,            $NULL,      $RW_,  null,
       N_POPUP,                      T_POPUPMENU,         $NULL,      $RW_,  null,
       N_REPAINT,                    T_CALLABLE,          $NULL,      $L__X, null,
       N_REQUESTFOCUS,               $FALSE,              $INTEGER,   $RW_,  null,
       N_RESIZABLE,                  $TRUE,               $INTEGER,   $RW_,  null,
       N_ROOT,                       T_OBJECT,            $NULL,      $LR__, null,
       N_SCREEN,                     T_OBJECT,            $NULL,      $RW_,  null,
       N_SHAPE,                      T_PATH,              $NULL,      $RW_,  null,
       N_SHOWING,                    $FALSE,              $INTEGER,   $LR__, null,
       N_SIZE,                       $DEFAULTSIZE,        $DIMENSION, $RW_,  null,
       N_TAG,                        T_STRING,            $NULL,      $RW_,  null,
       N_TITLE,                      T_STRING,            $NULL,      $RW_,  null,
       N_VALIDATE,                   $TRUE,               $INTEGER,   $RW_,  null,
       N_UIMKEY,                     T_STRING,            $NULL,      $RW_,  null,
       N_VISIBLE,                    $FALSE,              $INTEGER,   $RW_,  null,

       T_FILEDIALOG,                 "26",                $DICT,      $L___, T_FILEDIALOG,
       null,                         "-1",                $GROWTO,    null,  null,
       N_MAJOR,                      $COMPONENT,          $INTEGER,   $LR__, null,
       N_MINOR,                      $FILEDIALOG,         $INTEGER,   $LR__, null,
       N_AUTODISPOSE,                $FALSE,              $INTEGER,   $RW_,  null,
       N_BACKGROUND,                 T_COLOR,             $NULL,      $LR__, null,
       N_COMPONENTS,                 T_DICT,              $NULL,      $LR__, null,
       N_DIRECTORY,                  T_STRING,            $NULL,      $RW_,  null,
       N_DISPOSE,                    $FALSE,              $INTEGER,   $RW_,  null,
       N_ENABLED,                    $TRUE,               $INTEGER,   $RW_,  null,
       N_ETC,                        T_OBJECT,            $NULL,      $LR__, null,
       N_FILE,                       T_STRING,            $NULL,      $RW_,  null,
       N_FILTERS,                    T_ARRAY,             $NULL,      $RW_,  null,
       N_FONT,                       T_OBJECT,            $NULL,      $LR__, null,
       N_FOREGROUND,                 T_COLOR,             $NULL,      $LR__, null,
       N_LAYOUTMANAGER,              T_BORDERLAYOUT,      $NULL,      $LR__, null,
       N_LOCATION,                   T_POINT,             $NULL,      $RW_,  null,
       N_MODE,                       $YOIX_LOAD,          $INTEGER,   $RW_,  null,
       N_MODEL,                      "0",                 $INTEGER,   $LR__, null,
       N_PARENT,                     T_OBJECT,            $NULL,      $RW_,  null,
       N_ROOT,                       T_OBJECT,            $NULL,      $LR__, null,
       N_SCREEN,                     T_OBJECT,            $NULL,      $RW_,  null,
       N_SHOWING,                    $FALSE,              $INTEGER,   $LR__, null,
       N_SIZE,                       T_DIMENSION,         $NULL,      $RW_,  null,
       N_TAG,                        T_STRING,            $NULL,      $RW_,  null,
       N_TOYOIXPATH,                 $FALSE,              $INTEGER,   $RW_,  null,
       N_UIMKEY,                     T_STRING,            $NULL,      $RW_,  null,
       N_VISIBLE,                    $FALSE,              $INTEGER,   $RW_,  null,

       T_FRAME,                      "45",                $DICT,      $L___, T_FRAME,
       null,                         "-1",                $GROWTO,    null,  null,
       N_MAJOR,                      $COMPONENT,          $INTEGER,   $LR__, null,
       N_MINOR,                      $FRAME,              $INTEGER,   $LR__, null,
       N_AUTODEICONIFY,              $TRUE,               $INTEGER,   $RW_,  null,
       N_AUTODISPOSE,                $FALSE,              $INTEGER,   $RW_,  null,
       N_AUTORAISE,                  $TRUE,               $INTEGER,   $RW_,  null,
       N_BACKGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_BACKGROUNDHINTS,            $TILEHINT,           $INTEGER,   $RW_,  null,
       N_BACKGROUNDIMAGE,            T_OBJECT,            $NULL,      $RW_,  null,
       N_COMPONENTS,                 T_DICT,              $NULL,      $LR__, null,
       N_CURSOR,                     $STANDARDCURSOR,     $OBJECT,    $RW_,  null,
       N_DECORATIONSTYLE,            "1",                 $INTEGER,   $RW_,  null,
       N_DISPOSE,                    $FALSE,              $INTEGER,   $RW_,  null,
       N_ENABLED,                    $TRUE,               $INTEGER,   $RW_,  null,
       N_ETC,                        T_OBJECT,            $NULL,      $LR__, null,
       N_FIRSTFOCUS,                 $TRUE,               $INTEGER,   $RW_,  null,
       N_FOCUSABLE,                  T_OBJECT,            $NULL,      $RW_,  null,
       N_FOCUSOWNER,                 $FALSE,              $INTEGER,   $LR__, null,
       N_FONT,                       T_OBJECT,            $NULL,      $RW_,  null,
       N_FOREGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_FRONTTOBACK,                $TRUE,               $INTEGER,   $RW_,  null,
       N_FULLSCREEN,                 $FALSE,              $INTEGER,   $RW_,  null,
       N_GRAPHICS,                   T_GRAPHICS,          $NULL,      $RW_,  null,
       N_ICONIFIED,                  $FALSE,              $INTEGER,   $RW_,  null,
       N_LAYOUT,                     T_ARRAY,             $NULL,      $RW_,  null,
       N_LAYOUTMANAGER,              T_BORDERLAYOUT,      $DECLARE,   $RW_,  null,
       N_LOCATION,                   $DEFAULTLOCATION,    $POINT,     $RW_,  null,
       N_MAXIMIZED,                  $FALSE,              $INTEGER,   $RW_,  null,
       N_MENUBAR,                    T_MENUBAR,           $NULL,      $RW_,  null,
       N_NEXTCARD,                   T_OBJECT,            $NULL,      $RW_,  null,
       N_PAINT,                      T_CALLABLE,          $NULL,      $RWX,  null,
       N_PARENT,                     T_OBJECT,            $NULL,      $RW_,  null,
       N_POPUP,                      T_POPUPMENU,         $NULL,      $RW_,  null,
       N_REPAINT,                    T_CALLABLE,          $NULL,      $L__X, null,
       N_REQUESTFOCUS,               $FALSE,              $INTEGER,   $RW_,  null,
       N_RESIZABLE,                  $TRUE,               $INTEGER,   $RW_,  null,
       N_ROOT,                       T_OBJECT,            $NULL,      $LR__, null,
       N_SCREEN,                     T_OBJECT,            $NULL,      $RW_,  null,
       N_SHAPE,                      T_PATH,              $NULL,      $RW_,  null,
       N_SHOWING,                    $FALSE,              $INTEGER,   $LR__, null,
       N_SIZE,                       $DEFAULTSIZE,        $DIMENSION, $RW_,  null,
       N_TAG,                        T_STRING,            $NULL,      $RW_,  null,
       N_TITLE,                      T_STRING,            $NULL,      $RW_,  null,
       N_UIMKEY,                     T_STRING,            $NULL,      $RW_,  null,
       N_VALIDATE,                   $TRUE,               $INTEGER,   $RW_,  null,
       N_VISIBLE,                    $FALSE,              $INTEGER,   $RW_,  null,

       T_LABEL,                      "22",                $DICT,      $L___, T_LABEL,
       null,                         "-1",                $GROWTO,    null,  null,
       N_MAJOR,                      $COMPONENT,          $INTEGER,   $LR__, null,
       N_MINOR,                      $LABEL,              $INTEGER,   $LR__, null,
       N_ALIGNMENT,                  $YOIX_LEFT,          $INTEGER,   $RW_,  null,
       N_AUTOTRIM,                   $FALSE,              $INTEGER,   $RW_,  null,
       N_BACKGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_CURSOR,                     $STANDARDCURSOR,     $OBJECT,    $RW_,  null,
       N_ENABLED,                    $TRUE,               $INTEGER,   $RW_,  null,
       N_ETC,                        T_OBJECT,            $NULL,      $LR__, null,
       N_FOCUSABLE,                  T_OBJECT,            $NULL,      $RW_,  null,
       N_FOCUSOWNER,                 $FALSE,              $INTEGER,   $LR__, null,
       N_FONT,                       T_OBJECT,            $NULL,      $RW_,  null,
       N_FOREGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_LOCATION,                   T_POINT,             $NULL,      $RW_,  null,
       N_POPUP,                      T_POPUPMENU,         $NULL,      $RW_,  null,
       N_REQUESTFOCUS,               $FALSE,              $INTEGER,   $RW_,  null,
       N_ROOT,                       T_OBJECT,            $NULL,      $LR__, null,
       N_SHOWING,                    $FALSE,              $INTEGER,   $LR__, null,
       N_SIZE,                       T_DIMENSION,         $NULL,      $RW_,  null,
       N_TAG,                        T_STRING,            $NULL,      $RW_,  null,
       N_TEXT,                       T_STRING,            $NULL,      $RW_,  null,
       N_UIMKEY,                     T_STRING,            $NULL,      $RW_,  null,
       N_VISIBLE,                    $TRUE,               $INTEGER,   $RW_,  null,

       T_LIST,                       "27",                $DICT,      $L___, T_LIST,
       null,                         "-1",                $GROWTO,    null,  null,
       N_MAJOR,                      $COMPONENT,          $INTEGER,   $LR__, null,
       N_MINOR,                      $LIST,               $INTEGER,   $LR__, null,
       N_BACKGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_CURSOR,                     $STANDARDCURSOR,     $OBJECT,    $RW_,  null,
       N_ENABLED,                    $TRUE,               $INTEGER,   $RW_,  null,
       N_ETC,                        T_OBJECT,            $NULL,      $LR__, null,
       N_FOCUSABLE,                  T_OBJECT,            $NULL,      $RW_,  null,
       N_FOCUSOWNER,                 $FALSE,              $INTEGER,   $LR__, null,
       N_FONT,                       T_OBJECT,            $NULL,      $RW_,  null,
       N_FOREGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_INDEX,                      "-1",                $INTEGER,   $RW_,  null,
       N_ITEMS,                      T_ARRAY,             $NULL,      $RW_,  null,
       N_LABELS,                     T_ARRAY,             $NULL,      $RW_,  null,
       N_LOCATION,                   T_POINT,             $NULL,      $RW_,  null,
       N_MAPPINGS,                   T_ARRAY,             $NULL,      $RW_,  null,
       N_MULTIPLEMODE,               $FALSE,              $INTEGER,   $RW_,  null,
       N_POPUP,                      T_POPUPMENU,         $NULL,      $RW_,  null,
       N_REQUESTFOCUS,               $FALSE,              $INTEGER,   $RW_,  null,
       N_ROOT,                       T_OBJECT,            $NULL,      $LR__, null,
       N_ROWS,                       "1",                 $INTEGER,   $RW_,  null,
       N_SCROLL,                     $YOIX_BOTH,          $INTEGER,   $RW_,  null,
       N_SELECTED,                   T_OBJECT,            $NULL,      $RW_,  null,
       N_SHOWING,                    $FALSE,              $INTEGER,   $LR__, null,
       N_SIZE,                       T_DIMENSION,         $NULL,      $RW_,  null,
       N_TAG,                        T_STRING,            $NULL,      $RW_,  null,
       N_UIMKEY,                     T_STRING,            $NULL,      $RW_,  null,
       N_VISIBLE,                    $TRUE,               $INTEGER,   $RW_,  null,

       T_PANEL,                      "33",                $DICT,      $L___, T_PANEL,
       null,                         "-1",                $GROWTO,    null,  null,
       N_MAJOR,                      $COMPONENT,          $INTEGER,   $LR__, null,
       N_MINOR,                      $PANEL,              $INTEGER,   $LR__, null,
       N_BACKGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_BACKGROUNDHINTS,            $TILEHINT,           $INTEGER,   $RW_,  null,
       N_BACKGROUNDIMAGE,            T_OBJECT,            $NULL,      $RW_,  null,
       N_COMPONENTS,                 T_DICT,              $NULL,      $LR__, null,
       N_CURSOR,                     $STANDARDCURSOR,     $OBJECT,    $RW_,  null,
       N_ENABLED,                    $TRUE,               $INTEGER,   $RW_,  null,
       N_ETC,                        T_OBJECT,            $NULL,      $LR__, null,
       N_FOCUSABLE,                  T_OBJECT,            $NULL,      $RW_,  null,
       N_FOCUSOWNER,                 $FALSE,              $INTEGER,   $LR__, null,
       N_FONT,                       T_OBJECT,            $NULL,      $RW_,  null,
       N_FOREGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_FRONTTOBACK,                $TRUE,               $INTEGER,   $RW_,  null,
       N_GRAPHICS,                   T_GRAPHICS,          $NULL,      $RW_,  null,
       N_LAYOUT,                     T_ARRAY,             $NULL,      $RW_,  null,
       N_LAYOUTMANAGER,              T_FLOWLAYOUT,        $DECLARE,   $RW_,  null,
       N_LOCATION,                   T_POINT,             $NULL,      $RW_,  null,
       N_MAXIMUMSIZE,                T_DIMENSION,         $NULL,      $RW_,  null,
       N_MINIMUMSIZE,                T_DIMENSION,         $NULL,      $RW_,  null,
       N_NEXTCARD,                   T_OBJECT,            $NULL,      $RW_,  null,
       N_PAINT,                      T_CALLABLE,          $NULL,      $RWX,  null,
       N_POPUP,                      T_POPUPMENU,         $NULL,      $RW_,  null,
       N_PREFERREDSIZE,              T_DIMENSION,         $NULL,      $RW_,  null,
       N_REPAINT,                    T_CALLABLE,          $NULL,      $L__X, null,
       N_REQUESTFOCUS,               $FALSE,              $INTEGER,   $RW_,  null,
       N_ROOT,                       T_OBJECT,            $NULL,      $LR__, null,
       N_SHOWING,                    $FALSE,              $INTEGER,   $LR__, null,
       N_SIZE,                       T_DIMENSION,         $NULL,      $RW_,  null,
       N_TAG,                        T_STRING,            $NULL,      $RW_,  null,
       N_UIMKEY,                     T_STRING,            $NULL,      $RW_,  null,
       N_VALIDATE,                   $TRUE,               $INTEGER,   $RW_,  null,
       N_VISIBLE,                    $TRUE,               $INTEGER,   $RW_,  null,

       T_SCROLLBAR,                  "27",                $DICT,      $L___, T_SCROLLBAR,
       null,                         "-1",                $GROWTO,    null,  null,
       N_MAJOR,                      $COMPONENT,          $INTEGER,   $LR__, null,
       N_MINOR,                      $SCROLLBAR,          $INTEGER,   $LR__, null,
       N_BACKGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_BLOCKINCREMENT,             "10",                $INTEGER,   $RW_,  null,
       N_COMPRESSEVENTS,             N_ADJUSTCHANGED,     $OBJECT,    $RW_,  null,
       N_CURSOR,                     $STANDARDCURSOR,     $OBJECT,    $RW_,  null,
       N_ENABLED,                    $TRUE,               $INTEGER,   $RW_,  null,
       N_ETC,                        T_OBJECT,            $NULL,      $LR__, null,
       N_FOCUSABLE,                  T_OBJECT,            $NULL,      $RW_,  null,
       N_FOCUSOWNER,                 $FALSE,              $INTEGER,   $LR__, null,
       N_FONT,                       T_OBJECT,            $NULL,      $RW_,  null,
       N_FOREGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_LOCATION,                   T_POINT,             $NULL,      $RW_,  null,
       N_MAXIMUM,                    "100",               $INTEGER,   $RW_,  null,
       N_MINIMUM,                    "0",                 $INTEGER,   $RW_,  null,
       N_ORIENTATION,                $YOIX_VERTICAL,      $INTEGER,   $RW_,  null,
       N_REQUESTFOCUS,               $FALSE,              $INTEGER,   $RW_,  null,
       N_ROOT,                       T_OBJECT,            $NULL,      $LR__, null,
       N_SETVALUES,                  T_CALLABLE,          $NULL,      $L__X, null,
       N_SHOWING,                    $FALSE,              $INTEGER,   $LR__, null,
       N_SIZE,                       T_DIMENSION,         $NULL,      $RW_,  null,
       N_TAG,                        T_STRING,            $NULL,      $RW_,  null,
       N_UIMKEY,                     T_STRING,            $NULL,      $RW_,  null,
       N_UNITINCREMENT,              "1",                 $INTEGER,   $RW_,  null,
       N_VALUE,                      "0",                 $INTEGER,   $RW_,  null,
       N_VISIBLE,                    $TRUE,               $INTEGER,   $RW_,  null,
       N_VISIBLEAMOUNT,              "10",                $INTEGER,   $RW_,  null,

       T_SCROLLPANE,                 "25",                $DICT,      $L___, T_SCROLLPANE,
       null,                         "-1",                $GROWTO,    null,  null,
       N_MAJOR,                      $COMPONENT,          $INTEGER,   $LR__, null,
       N_MINOR,                      $SCROLLPANE,         $INTEGER,   $LR__, null,
       N_BACKGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_COMPONENTS,                 T_DICT,              $NULL,      $LR__, null,
       N_CURSOR,                     $STANDARDCURSOR,     $OBJECT,    $RW_,  null,
       N_ENABLED,                    $TRUE,               $INTEGER,   $RW_,  null,
       N_ETC,                        T_OBJECT,            $NULL,      $LR__, null,
       N_FOCUSABLE,                  T_OBJECT,            $NULL,      $RW_,  null,
       N_FOCUSOWNER,                 $FALSE,              $INTEGER,   $LR__, null,
       N_FONT,                       T_OBJECT,            $NULL,      $RW_,  null,
       N_FOREGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_FRONTTOBACK,                $TRUE,               $INTEGER,   $RW_,  null,
       N_LAYOUT,                     T_ARRAY,             $NULL,      $RW_,  null,
       N_LAYOUTMANAGER,              T_BORDERLAYOUT,      $NULL,      $LR__, null,
       N_LOCATION,                   T_POINT,             $NULL,      $RW_,  null,
       N_POPUP,                      T_POPUPMENU,         $NULL,      $RW_,  null,
       N_REQUESTFOCUS,               $FALSE,              $INTEGER,   $RW_,  null,
       N_ROOT,                       T_OBJECT,            $NULL,      $LR__, null,
       N_SCROLL,                     $YOIX_ALWAYS,        $INTEGER,   $RW_,  null,
       N_SHOWING,                    $FALSE,              $INTEGER,   $LR__, null,
       N_SIZE,                       T_DIMENSION,         $NULL,      $RW_,  null,
       N_TAG,                        T_STRING,            $NULL,      $RW_,  null,
       N_UIMKEY,                     T_STRING,            $NULL,      $RW_,  null,
       N_VALIDATE,                   $TRUE,               $INTEGER,   $RW_,  null,
       N_VISIBLE,                    $TRUE,               $INTEGER,   $RW_,  null,

       T_TABLECOLUMN,                "43",                $DICT,      $L___, T_TABLECOLUMN,
       null,                         "-1",                $GROWTO,    null,  null,
       N_MAJOR,                      $COMPONENT,          $INTEGER,   $LR__, null,
       N_MINOR,                      $TABLECOLUMN,        $INTEGER,   $LR__, null,
       N_AFTERLOAD,                  T_CALLABLE,          $NULL,      $RWX,  null,
       N_ALIGNMENT,                  $YOIX_LEFT,          $INTEGER,   $RW_,  null,
       N_BACKGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_BORDER,                     T_OBJECT,            $NULL,      $RW_,  null,
       N_BORDERCOLOR,                T_COLOR,             $NULL,      $RW_,  null,
       N_CELLSIZE,                   T_DIMENSION,         $DECLARE,   $LR__, null,
       N_COLUMNS,                    "0",                 $INTEGER,   $RW_,  null,
       N_CURSOR,                     $STANDARDCURSOR,     $OBJECT,    $RW_,  null,
       N_ENABLED,                    $TRUE,               $INTEGER,   $RW_,  null,
       N_ETC,                        T_OBJECT,            $NULL,      $LR__, null,
       N_EXTENT,                     T_DIMENSION,         $DECLARE,   $LR__, null,
       N_FOCUSABLE,                  T_OBJECT,            $NULL,      $RW_,  null,
       N_FOCUSOWNER,                 $FALSE,              $INTEGER,   $LR__, null,
       N_FONT,                       T_OBJECT,            $NULL,      $RW_,  null,
       N_FOREGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_HIGHLIGHTED,                T_OBJECT,            $NULL,      $RW_,  null,
       N_INDEX,                      "-1",                $INTEGER,   $RW_,  null,
       N_INSETS,                     $MEDIUMINSETS,       $OBJECT,    $RW_,  null,
       N_IPAD,                       T_OBJECT,            $NULL,      $RW_,  null,
       N_LOCATION,                   T_POINT,             $NULL,      $RW_,  null,
       N_MAXIMUMSIZE,                T_DIMENSION,         $NULL,      $RW_,  null,
       N_MINIMUMSIZE,                T_DIMENSION,         $NULL,      $RW_,  null,
       N_ORIGIN,                     T_POINT,             $DECLARE,   $RW_,  null,
       N_POPUP,                      T_POPUPMENU,         $NULL,      $RW_,  null,
       N_PREFERREDSIZE,              T_DIMENSION,         $NULL,      $RW_,  null,
       N_REQUESTFOCUS,               $FALSE,              $INTEGER,   $RW_,  null,
       N_ROOT,                       T_OBJECT,            $NULL,      $LR__, null,
       N_ROWPROPERTIES,              T_ROWPROPERTIES,     $NULL,      $RW_,  null,
       N_ROWS,                       "0",                 $INTEGER,   $RW_,  null,
       N_SAVEGRAPHICS,               $FALSE,              $INTEGER,   $RW_,  null,
       N_SELECTED,                   T_STRING,            $NULL,      $RW_,  null,
       N_SHOWING,                    $FALSE,              $INTEGER,   $LR__, null,
       N_SIZE,                       T_DIMENSION,         $NULL,      $RW_,  null,
       N_STATE,                      $FALSE,              $INTEGER,   $RW_,  null,
       N_TAG,                        T_STRING,            $NULL,      $RW_,  null,
       N_TEXT,                       T_STRING,            $NULL,      $LR__, null,
       N_UIMKEY,                     T_STRING,            $NULL,      $RW_,  null,
       N_VALUE,                      T_CALLABLE,          $NULL,      $L__X, null,
       N_VIEWPORT,                   T_RECTANGLE,         $DECLARE,   $LR__, null,
       N_VISIBLE,                    $TRUE,               $INTEGER,   $RW_,  null,
       N_VISITCOLOR,                 T_COLOR,             $NULL,      $RW_,  null,

       T_TABLEMANAGER,               "42",                $DICT,      $L___, T_TABLEMANAGER,
       null,                         "-1",                $GROWTO,    null,  null,
       N_MAJOR,                      $COMPONENT,          $INTEGER,   $LR__, null,
       N_MINOR,                      $TABLEMANAGER,       $INTEGER,   $LR__, null,
       N_AFTERLOAD,                  T_CALLABLE,          $NULL,      $RWX,  null,
       N_BACKGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_CELLSIZE,                   T_DIMENSION,         $DECLARE,   $LR__, null,
       N_CLICKRADIUS,                "3",                 $DOUBLE,    $RW_,  null,
       N_COMPONENTS,                 T_DICT,              $NULL,      $LR__, null,
       N_CURSOR,                     $STANDARDCURSOR,     $OBJECT,    $RW_,  null,
       N_DISPLAYED,                  T_STRING,            $NULL,      $LR__, null,
       N_ENABLED,                    $TRUE,               $INTEGER,   $RW_,  null,
       N_ETC,                        T_OBJECT,            $NULL,      $LR__, null,
       N_EXTENT,                     T_DIMENSION,         $DECLARE,   $LR__, null,
       N_FOCUSABLE,                  T_OBJECT,            $NULL,      $RW_,  null,
       N_FOCUSOWNER,                 $FALSE,              $INTEGER,   $LR__, null,
       N_FONT,                       T_OBJECT,            $NULL,      $RW_,  null,
       N_FOREGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_FRONTTOBACK,                $TRUE,               $INTEGER,   $RW_,  null,
       N_HIGHLIGHTED,                T_OBJECT,            $NULL,      $RW_,  null,
       N_HTML,                       T_CALLABLE,          $NULL,      $L__X, null,
       N_INDEX,                      T_OBJECT,            $NULL,      $RW_,  null,
       N_INPUTFILTER,                T_OBJECT,            $NULL,      $RW_,  null,
       N_LAYOUT,                     T_ARRAY,             $NULL,      $RW_,  null,
       N_LAYOUTMANAGER,              T_FLOWLAYOUT,        $DECLARE,   $RW_,  null,
       N_LOCATION,                   T_POINT,             $NULL,      $RW_,  null,
       N_NEXTCARD,                   T_OBJECT,            $NULL,      $RW_,  null,
       N_ORIGIN,                     T_POINT,             $DECLARE,   $RW_,  null,
       N_OUTPUTFILTER,               T_OBJECT,            $NULL,      $RW_,  null,
       N_POPUP,                      T_POPUPMENU,         $NULL,      $RW_,  null,
       N_REQUESTFOCUS,               $FALSE,              $INTEGER,   $RW_,  null,
       N_ROOT,                       T_OBJECT,            $NULL,      $LR__, null,
       N_ROWPROPERTIES,              T_ROWPROPERTIES,     $NULL,      $RW_,  null,
       N_SAVEGRAPHICS,               $FALSE,              $INTEGER,   $RW_,  null,
       N_SELECTED,                   T_OBJECT,            $NULL,      $LR__, null,
       N_SHOWING,                    $FALSE,              $INTEGER,   $LR__, null,
       N_SIZE,                       T_DIMENSION,         $NULL,      $RW_,  null,
       N_SYNCVIEWPORT,               T_CALLABLE,          $NULL,      $RWX,  null,
       N_TAG,                        T_STRING,            $NULL,      $RW_,  null,
       N_TEXT,                       T_STRING,            $NULL,      $RW_,  null,
       N_UIMKEY,                     T_STRING,            $NULL,      $RW_,  null,
       N_VALIDATE,                   $TRUE,               $INTEGER,   $RW_,  null,
       N_VIEWPORT,                   T_RECTANGLE,         $DECLARE,   $LR__, null,
       N_VISIBLE,                    $TRUE,               $INTEGER,   $RW_,  null,

       T_TEXTAREA,                   "28",                $DICT,      $L___, T_TEXTAREA,
       null,                         "-1",                $GROWTO,    null,  null,
       N_MAJOR,                      $COMPONENT,          $INTEGER,   $LR__, null,
       N_MINOR,                      $TEXTAREA,           $INTEGER,   $LR__, null,
       N_AUTOTRIM,                   $FALSE,              $INTEGER,   $RW_,  null,
       N_BACKGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_CARET,                      "0",                 $INTEGER,   $RW_,  null,
       N_COLUMNS,                    "80",                $INTEGER,   $RW_,  null,
       N_CURSOR,                     $STANDARDCURSOR,     $OBJECT,    $RW_,  null,
       N_EDIT,                       $TRUE,               $INTEGER,   $RW_,  null,
       N_ENABLED,                    $TRUE,               $INTEGER,   $RW_,  null,
       N_ETC,                        T_OBJECT,            $NULL,      $LR__, null,
       N_FOCUSABLE,                  T_OBJECT,            $NULL,      $RW_,  null,
       N_FOCUSOWNER,                 $FALSE,              $INTEGER,   $LR__, null,
       N_FONT,                       T_OBJECT,            $NULL,      $RW_,  null,
       N_FOREGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_LOCATION,                   T_POINT,             $NULL,      $RW_,  null,
       N_POPUP,                      T_POPUPMENU,         $NULL,      $RW_,  null,
       N_REQUESTFOCUS,               $FALSE,              $INTEGER,   $RW_,  null,
       N_ROOT,                       T_OBJECT,            $NULL,      $LR__, null,
       N_ROWS,                       "5",                 $INTEGER,   $RW_,  null,
       N_SCROLL,                     $YOIX_BOTH,          $INTEGER,   $RW_,  null,
       N_SELECTED,                   T_STRING,            $NULL,      $RW_,  null,
       N_SELECTEDENDS,               T_ARRAY,             $NULL,      $RW_,  null,
       N_SHOWING,                    $FALSE,              $INTEGER,   $LR__, null,
       N_SIZE,                       T_DIMENSION,         $NULL,      $RW_,  null,
       N_TAG,                        T_STRING,            $NULL,      $RW_,  null,
       N_TEXT,                       T_STRING,            $NULL,      $RW_,  null,
       N_UIMKEY,                     T_STRING,            $NULL,      $RW_,  null,
       N_VISIBLE,                    $TRUE,               $INTEGER,   $RW_,  null,

       T_TEXTCANVAS,                 "43",                $DICT,      $L___, T_TEXTCANVAS,
       null,                         "-1",                $GROWTO,    null,  null,
       N_MAJOR,                      $COMPONENT,          $INTEGER,   $LR__, null,
       N_MINOR,                      $TEXTCANVAS,         $INTEGER,   $LR__, null,
       N_ALIGNMENT,                  $YOIX_LEFT,          $INTEGER,   $RW_,  null,
       N_AUTOTRIM,                   $FALSE,              $INTEGER,   $RW_,  null,
       N_BACKGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_BORDER,                     T_OBJECT,            $NULL,      $RW_,  null,
       N_BORDERCOLOR,                T_COLOR,             $NULL,      $RW_,  null,
       N_BUTTONMASK,                 $BUTTON1MASK,        $INTEGER,   $RW_,  null,
       N_CELLSIZE,                   T_DIMENSION,         $DECLARE,   $LR__, null,
       N_COLUMNS,                    "0",                 $INTEGER,   $RW_,  null,
       N_CURSOR,                     $STANDARDCURSOR,     $OBJECT,    $RW_,  null,
       N_ENABLED,                    $TRUE,               $INTEGER,   $RW_,  null,
       N_ETC,                        T_OBJECT,            $NULL,      $LR__, null,
       N_EXTENT,                     T_DIMENSION,         $DECLARE,   $LR__, null,
       N_FOCUSABLE,                  T_OBJECT,            $NULL,      $RW_,  null,
       N_FOCUSOWNER,                 $FALSE,              $INTEGER,   $LR__, null,
       N_FONT,                       T_OBJECT,            $NULL,      $RW_,  null,
       N_FOREGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_INSETS,                     $MEDIUMINSETS,       $OBJECT,    $RW_,  null,
       N_IPAD,                       T_OBJECT,            $NULL,      $RW_,  null,
       N_LOCATION,                   T_POINT,             $NULL,      $RW_,  null,
       N_MAXIMUMSIZE,                T_DIMENSION,         $NULL,      $RW_,  null,
       N_MINIMUMSIZE,                T_DIMENSION,         $NULL,      $RW_,  null,
       N_ORIGIN,                     T_POINT,             $DECLARE,   $RW_,  null,
       N_POPUP,                      T_POPUPMENU,         $NULL,      $RW_,  null,
       N_PREFERREDSIZE,              T_DIMENSION,         $NULL,      $RW_,  null,
       N_REQUESTFOCUS,               $FALSE,              $INTEGER,   $RW_,  null,
       N_ROOT,                       T_OBJECT,            $NULL,      $LR__, null,
       N_ROWS,                       "0",                 $INTEGER,   $RW_,  null,
       N_SAVEGRAPHICS,               $FALSE,              $INTEGER,   $RW_,  null,
       N_SHOWING,                    $FALSE,              $INTEGER,   $LR__, null,
       N_SIZE,                       T_DIMENSION,         $NULL,      $RW_,  null,
       N_STATE,                      $FALSE,              $INTEGER,   $RW_,  null,
       N_STICKY,                     $FALSE,              $INTEGER,   $RW_,  null,
       N_SYNCCOUNT,                  "0",                 $INTEGER,   $LR__, null,
       N_SYNCVIEWPORT,               T_CALLABLE,          $NULL,      $RWX,  null,
       N_TAG,                        T_STRING,            $NULL,      $RW_,  null,
       N_TEXT,                       T_STRING,            $NULL,      $RW_,  null,
       N_TEXTMODE,                   $YOIX_WORDMODE,      $INTEGER,   $RW_,  null,
       N_TEXTWRAP,                   $TRUE,               $INTEGER,   $RW_,  null,
       N_UIMKEY,                     T_STRING,            $NULL,      $RW_,  null,
       N_VIEWPORT,                   T_RECTANGLE,         $DECLARE,   $LR__, null,
       N_VISIBLE,                    $TRUE,               $INTEGER,   $RW_,  null,

       T_TEXTFIELD,                  "30",                $DICT,      $L___, T_TEXTFIELD,
       null,                         "-1",                $GROWTO,    null,  null,
       N_MAJOR,                      $COMPONENT,          $INTEGER,   $LR__, null,
       N_MINOR,                      $TEXTFIELD,          $INTEGER,   $LR__, null,
       N_AUTOTRIM,                   $FALSE,              $INTEGER,   $RW_,  null,
       N_BACKGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_CARET,                      "0",                 $INTEGER,   $RW_,  null,
       N_COLUMNS,                    "10",                $INTEGER,   $RW_,  null,
       N_CURSOR,                     $STANDARDCURSOR,     $OBJECT,    $RW_,  null,
       N_ECHO,                       "0",                 $INTEGER,   $RW_,  null,
       N_EDIT,                       $TRUE,               $INTEGER,   $RW_,  null,
       N_ENABLED,                    $TRUE,               $INTEGER,   $RW_,  null,
       N_ETC,                        T_OBJECT,            $NULL,      $LR__, null,
       N_FOCUSABLE,                  T_OBJECT,            $NULL,      $RW_,  null,
       N_FOCUSOWNER,                 $FALSE,              $INTEGER,   $LR__, null,
       N_FONT,                       T_OBJECT,            $NULL,      $RW_,  null,
       N_FOREGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_LOCATION,                   T_POINT,             $NULL,      $RW_,  null,
       N_MAXIMUMSIZE,                T_DIMENSION,         $NULL,      $RW_,  null,
       N_MINIMUMSIZE,                T_DIMENSION,         $NULL,      $RW_,  null,
       N_POPUP,                      T_POPUPMENU,         $NULL,      $RW_,  null,
       N_PREFERREDSIZE,              T_DIMENSION,         $NULL,      $RW_,  null,
       N_REQUESTFOCUS,               $FALSE,              $INTEGER,   $RW_,  null,
       N_ROOT,                       T_OBJECT,            $NULL,      $LR__, null,
       N_SELECTED,                   T_STRING,            $NULL,      $RW_,  null,
       N_SELECTEDENDS,               T_ARRAY,             $NULL,      $RW_,  null,
       N_SHOWING,                    $FALSE,              $INTEGER,   $LR__, null,
       N_SIZE,                       T_DIMENSION,         $NULL,      $RW_,  null,
       N_TAG,                        T_STRING,            $NULL,      $RW_,  null,
       N_TEXT,                       T_STRING,            $NULL,      $RW_,  null,
       N_UIMKEY,                     T_STRING,            $NULL,      $RW_,  null,
       N_VISIBLE,                    $TRUE,               $INTEGER,   $RW_,  null,

       T_TEXTTERM,                   "43",                $DICT,      $L___, T_TEXTTERM,
       null,                         "-1",                $GROWTO,    null,  null,
       N_MAJOR,                      $COMPONENT,          $INTEGER,   $LR__, null,
       N_MINOR,                      $TEXTTERM,           $INTEGER,   $LR__, null,
       N_AFTERNEWLINE,               T_FUNCTION,          $NULL,      $RWX,  null,
       N_ALIGNMENT,                  $YOIX_LEFT,          $INTEGER,   $RW_,  null,
       N_AUTOTRIM,                   $FALSE,              $INTEGER,   $RW_,  null,
       N_BACKGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_BORDER,                     T_OBJECT,            $NULL,      $RW_,  null,
       N_BORDERCOLOR,                T_COLOR,             $NULL,      $RW_,  null,
       N_CELLSIZE,                   T_DIMENSION,         $DECLARE,   $LR__, null,
       N_COLUMNS,                    "0",                 $INTEGER,   $RW_,  null,
       N_CURSOR,                     $STANDARDCURSOR,     $OBJECT,    $RW_,  null,
       N_EDIT,                       $TRUE,               $INTEGER,   $RW_,  null,
       N_ENABLED,                    $TRUE,               $INTEGER,   $RW_,  null,
       N_ETC,                        T_OBJECT,            $NULL,      $LR__, null,
       N_EXTENT,                     T_DIMENSION,         $DECLARE,   $LR__, null,
       N_FOCUSABLE,                  T_OBJECT,            $NULL,      $RW_,  null,
       N_FOCUSOWNER,                 $FALSE,              $INTEGER,   $LR__, null,
       N_FONT,                       T_OBJECT,            $NULL,      $RW_,  null,
       N_FOREGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_INSETS,                     $MEDIUMINSETS,       $OBJECT,    $RW_,  null,
       N_IPAD,                       T_OBJECT,            $NULL,      $RW_,  null,
       N_LOCATION,                   T_POINT,             $NULL,      $RW_,  null,
       N_MAXIMUMSIZE,                T_DIMENSION,         $NULL,      $RW_,  null,
       N_MINIMUMSIZE,                T_DIMENSION,         $NULL,      $RW_,  null,
       N_ORIGIN,                     T_POINT,             $DECLARE,   $RW_,  null,
       N_POPUP,                      T_POPUPMENU,         $NULL,      $RW_,  null,
       N_PREFERREDSIZE,              T_DIMENSION,         $NULL,      $RW_,  null,
       N_PROMPT,                     T_STRING,            $NULL,      $RW_,  null,
       N_REQUESTFOCUS,               $FALSE,              $INTEGER,   $RW_,  null,
       N_ROOT,                       T_OBJECT,            $NULL,      $LR__, null,
       N_ROWS,                       "0",                 $INTEGER,   $RW_,  null,
       N_SAVEGRAPHICS,               $FALSE,              $INTEGER,   $RW_,  null,
       N_SAVELINES,                  "0",                 $INTEGER,   $RW_,  null,
       N_SHOWING,                    $FALSE,              $INTEGER,   $LR__, null,
       N_SIZE,                       T_DIMENSION,         $NULL,      $RW_,  null,
       N_STATE,                      $FALSE,              $INTEGER,   $RW_,  null,
       N_SYNCCOUNT,                  "0",                 $INTEGER,   $LR__, null,
       N_SYNCVIEWPORT,               T_CALLABLE,          $NULL,      $RWX,  null,
       N_TAG,                        T_STRING,            $NULL,      $RW_,  null,
       N_TEXT,                       T_STRING,            $NULL,      $RW_,  null,
       N_UIMKEY,                     T_STRING,            $NULL,      $RW_,  null,
       N_VIEWPORT,                   T_RECTANGLE,         $DECLARE,   $LR__, null,
       N_VISIBLE,                    $TRUE,               $INTEGER,   $RW_,  null,

       T_WINDOW,                     "38",                $DICT,      $L___, T_WINDOW,
       null,                         "-1",                $GROWTO,    null,  null,
       N_MAJOR,                      $COMPONENT,          $INTEGER,   $LR__, null,
       N_MINOR,                      $WINDOW,             $INTEGER,   $LR__, null,
       N_AUTODISPOSE,                $FALSE,              $INTEGER,   $RW_,  null,
       N_AUTORAISE,                  $TRUE,               $INTEGER,   $RW_,  null,
       N_BACKGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_BACKGROUNDHINTS,            $TILEHINT,           $INTEGER,   $RW_,  null,
       N_BACKGROUNDIMAGE,            T_OBJECT,            $NULL,      $RW_,  null,
       N_COMPONENTS,                 T_DICT,              $NULL,      $LR__, null,
       N_CURSOR,                     $STANDARDCURSOR,     $OBJECT,    $RW_,  null,
       N_DISPOSE,                    $FALSE,              $INTEGER,   $RW_,  null,
       N_ENABLED,                    $TRUE,               $INTEGER,   $RW_,  null,
       N_ETC,                        T_OBJECT,            $NULL,      $LR__, null,
       N_FIRSTFOCUS,                 $TRUE,               $INTEGER,   $RW_,  null,
       N_FOCUSABLE,                  T_OBJECT,            $NULL,      $RW_,  null,
       N_FONT,                       T_OBJECT,            $NULL,      $RW_,  null,
       N_FOREGROUND,                 T_COLOR,             $NULL,      $RW_,  null,
       N_FRONTTOBACK,                $TRUE,               $INTEGER,   $RW_,  null,
       N_FULLSCREEN,                 $FALSE,              $INTEGER,   $RW_,  null,
       N_GRAPHICS,                   T_GRAPHICS,          $NULL,      $RW_,  null,
       N_LAYOUT,                     T_ARRAY,             $NULL,      $RW_,  null,
       N_LAYOUTMANAGER,              T_BORDERLAYOUT,      $DECLARE,   $RW_,  null,
       N_LOCATION,                   $DEFAULTLOCATION,    $POINT,     $RW_,  null,
       N_NEXTCARD,                   T_OBJECT,            $NULL,      $RW_,  null,
       N_PAINT,                      T_CALLABLE,          $NULL,      $RWX,  null,
       N_PARENT,                     T_OBJECT,            $NULL,      $RW_,  null,
       N_POPUP,                      T_POPUPMENU,         $NULL,      $RW_,  null,
       N_REPAINT,                    T_CALLABLE,          $NULL,      $L__X, null,
       N_REQUESTFOCUS,               $FALSE,              $INTEGER,   $RW_,  null,
       N_ROOT,                       T_OBJECT,            $NULL,      $LR__, null,
       N_SCREEN,                     T_OBJECT,            $NULL,      $RW_,  null,
       N_SHAPE,                      T_PATH,              $NULL,      $RW_,  null,
       N_SHOWING,                    $FALSE,              $INTEGER,   $LR__, null,
       N_SIZE,                       $DEFAULTSIZE,        $DIMENSION, $RW_,  null,
       N_TAG,                        T_STRING,            $NULL,      $RW_,  null,
       N_TITLE,                      T_STRING,            $NULL,      $RW_,  null,
       N_UIMKEY,                     T_STRING,            $NULL,      $RW_,  null,
       N_VALIDATE,                   $TRUE,               $INTEGER,   $RW_,  null,
       N_VISIBLE,                    $FALSE,              $INTEGER,   $RW_,  null,

    //
    // Swing compatibility types. $GET is a recent addition that's OK in
    // some instances, but if you're not 100% certain use $DUP.
    //

       T_CHECKBOXGROUP_SWING,        T_CHECKBOXGROUP,     $GET,       $L___, T_CHECKBOXGROUP_SWING,
       null,                         T_CHECKBOXGROUP,     $TYPENAME,  null,  null,

       T_CHECKBOX_SWING,             T_CHECKBOX,          $GET,       $L___, T_CHECKBOX_SWING,
       null,                         T_CHECKBOX,          $TYPENAME,  null,  null,

       T_SCROLLBAR_SWING,            T_SCROLLBAR,         $GET,       $L___, T_SCROLLBAR_SWING,
       null,                         T_SCROLLBAR,         $TYPENAME,  null,  null,
    };

    ///////////////////////////////////
    //
    // YoixModuleAWT Methods
    //
    ///////////////////////////////////

}

